#!/bin/bash

############################# SETTINGS ###############################

godot_installed_path=$HOME/godot/app
downloaded_filename=Godot.zip

#####################################################################

run(){

    version=`getconf LONG_BIT` #32 or 64 bit

    if $mono_version;
    then
        PATH_TO_GODOT_EXECUTABLE=$godot_installed_path/[Godot_v]* #The PATH to the Godot Executable
    else
        PATH_TO_GODOT_EXECUTABLE=$godot_installed_path #The PATH to the Godot Executable
    fi

    cd $PATH_TO_GODOT_EXECUTABLE #change to the directory where the Godot execuable is located

    GODOT_EXECUTABLE=*.$version #the godot executable will be the one that finishes with $GODOT_VERSION
    chmod +x $GODOT_EXECUTABLE #gives the permission to run

   ./$GODOT_EXECUTABLE& #execute the executable and lauches it in another process

}

install(){

    UNAME=$( command -v uname)

    case $( "${UNAME}" | tr '[:upper:]' '[:lower:]') in
        linux*)
            os=linux ;;
        darwin*)
            os=osx ;;
        msys*|cygwin*|mingw*)
        # or possible 'bash on windows'
            os=windows ;;
        nt|win*)
            os=windows ;;
        *)
            os=windows ;;
    esac

    version=`getconf LONG_BIT` #32 or 64 bit

    #Downloads ans extracts the files
    echo "Downloading Godot..."
    godot_downloader.py $os $version $mono_version $downloaded_filename

    #Removes the zip files and $godot_installed_path directory
    echo "Removing the downloaded zip file..."
    rm -f $downloaded_filename
    echo "Replacing the old files with the new ones..."
    rm -r $godot_installed_path
    mkdir -p $godot_installed_path
    #moves the file to a destination
    mv Godot_v* $godot_installed_path

    launcher # Automatically creates a launcher

    echo "Done!"

}

create-linux-launcher(){

    DIR=~/.local/share/applications
    FILE=godot.desktop

    ICON_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd )"


    if [[ -f "$DIR/$FILE" ]]; then
        echo "Desktop launcher already created in $DIR/$FILE"
    else
        touch $DIR/$FILE
        echo -e "[Desktop Entry]\nName=Godot Engine\nExec=$HOME/git/Godot_startup_script/scripts/godot\nComment=A FOSS Multi-platform 2D and 3D game engine\nTerminal=false\nIcon=$ICON_DIR/512px-Godot_icon.svg\nType=Application" > $DIR/$FILE
    fi
}

create-osx-launcher(){

    echo "WIP"

}


create-windows-launcher(){
    
    echo "WIP"

}

launcher(){

    UNAME=$( command -v uname)

    case $( "${UNAME}" | tr '[:upper:]' '[:lower:]') in
        linux*)
            create-linux-launcher ;;
        darwin*)
            create-osx-launcher ;;
        msys*|cygwin*|mingw*)
        # or possible 'bash on windows'
            create-windows-launcher ;;
        nt|win*)
            create-windows-launcher ;;
        *)
            create-windows-launcher ;;
    esac

}

###### main

case "$1" in
    "")
        run ;; 
    "install")
        if [[ $2==mono ]];
        then
            mono_version=true
        else
            mono_version=false
        fi
        install ;;
    "launcher")
        launcher ;;
esac
