#!/bin/sh

version=64 #32 or 64 bit
mono_version=true #true or false otherwise will crash
godot_installed_path=$HOME/godot/app


if $mono_version;
then
    PATH_TO_GODOT_EXECUTABLE=$godot_installed_path/[Godot_v]* #The PATH to the Godot Executable
else
    PATH_TO_GODOT_EXECUTABLE=$godot_installed_path #The PATH to the Godot Executable
fi

cd $PATH_TO_GODOT_EXECUTABLE #change to the directory where the Godot execuable is located

GODOT_EXECUTABLE=*.$version #the godot executable will be the one that finishes with $GODOT_VERSION

chmod +x $GODOT_EXECUTABLE #gives the permission to run

./$GODOT_EXECUTABLE& #execute the executable and lauches it in another process
